# Model arguments
model_name_or_path: allenai/OLMo-2-0425-1B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: dclm
dataset_prompt_column: text
system_prompt: "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the questions."

# GRPO trainer config
bf16: true
use_vllm: true
vllm_mode: colocate
do_eval: true
eval_strategy: steps
eval_steps: 30
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: synthetic_data_generator
hub_strategy: every_save
learning_rate: 1.0e-06
beta: 0.005
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
max_prompt_length: 2048
max_completion_length: 2048
max_steps: 2000
num_generations: 8 # must be divisible by per_device_train_batch_size x number_of_gpus, see https://github.com/huggingface/trl/pull/2776#issue-2833772774
num_train_epochs: 20
output_dir: /tmp/synthetic_data_generator_OLMo2-1B_grpo
overwrite_output_dir: true
per_device_eval_batch_size: 16
per_device_train_batch_size: 8
push_to_hub: false
report_to:
- wandb
reward_funcs:
- dataman
- format
- bert_score
- structure
- length
reward_weights:
- 3.0
- 1.0
- 1.0
- 1.0
- 1.0
save_strategy: steps
save_steps: 60
save_total_limit: 100
seed: 42
temperature: 1.0
top_p: 0.9
warmup_ratio: 0.1